/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArtifactsRouteImport } from './routes/artifacts'
import { Route as BotsRouteImport } from './routes/bots'
import { Route as CapabilitiesRouteImport } from './routes/capabilities'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as KanbanRouteImport } from './routes/kanban'
import { Route as MemoryRouteImport } from './routes/memory'
import { Route as MessagingRouteImport } from './routes/messaging'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StatusRouteImport } from './routes/status'
import { Route as CSessionIdRouteImport } from './routes/c.$sessionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsRoute = ArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsRoute = BotsRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => rootRouteImport,
} as any)
const CapabilitiesRoute = CapabilitiesRouteImport.update({
  id: '/capabilities',
  path: '/capabilities',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const KanbanRoute = KanbanRouteImport.update({
  id: '/kanban',
  path: '/kanban',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoryRoute = MemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagingRoute = MessagingRouteImport.update({
  id: '/messaging',
  path: '/messaging',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const CSessionIdRoute = CSessionIdRouteImport.update({
  id: '/c/$sessionId',
  path: '/c/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/bots': typeof BotsRoute
  '/capabilities': typeof CapabilitiesRoute
  '/jobs': typeof JobsRoute
  '/kanban': typeof KanbanRoute
  '/memory': typeof MemoryRoute
  '/messaging': typeof MessagingRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/c/$sessionId': typeof CSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/bots': typeof BotsRoute
  '/capabilities': typeof CapabilitiesRoute
  '/jobs': typeof JobsRoute
  '/kanban': typeof KanbanRoute
  '/memory': typeof MemoryRoute
  '/messaging': typeof MessagingRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/c/$sessionId': typeof CSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/bots': typeof BotsRoute
  '/capabilities': typeof CapabilitiesRoute
  '/jobs': typeof JobsRoute
  '/kanban': typeof KanbanRoute
  '/memory': typeof MemoryRoute
  '/messaging': typeof MessagingRoute
  '/settings': typeof SettingsRoute
  '/status': typeof StatusRoute
  '/c/$sessionId': typeof CSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artifacts'
    | '/bots'
    | '/capabilities'
    | '/jobs'
    | '/kanban'
    | '/memory'
    | '/messaging'
    | '/settings'
    | '/status'
    | '/c/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artifacts'
    | '/bots'
    | '/capabilities'
    | '/jobs'
    | '/kanban'
    | '/memory'
    | '/messaging'
    | '/settings'
    | '/status'
    | '/c/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/artifacts'
    | '/bots'
    | '/capabilities'
    | '/jobs'
    | '/kanban'
    | '/memory'
    | '/messaging'
    | '/settings'
    | '/status'
    | '/c/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtifactsRoute: typeof ArtifactsRoute
  BotsRoute: typeof BotsRoute
  CapabilitiesRoute: typeof CapabilitiesRoute
  JobsRoute: typeof JobsRoute
  KanbanRoute: typeof KanbanRoute
  MemoryRoute: typeof MemoryRoute
  MessagingRoute: typeof MessagingRoute
  SettingsRoute: typeof SettingsRoute
  StatusRoute: typeof StatusRoute
  CSessionIdRoute: typeof CSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts': {
      id: '/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof ArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots': {
      id: '/bots'
      path: '/bots'
      fullPath: '/bots'
      preLoaderRoute: typeof BotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capabilities': {
      id: '/capabilities'
      path: '/capabilities'
      fullPath: '/capabilities'
      preLoaderRoute: typeof CapabilitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kanban': {
      id: '/kanban'
      path: '/kanban'
      fullPath: '/kanban'
      preLoaderRoute: typeof KanbanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memory': {
      id: '/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof MemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messaging': {
      id: '/messaging'
      path: '/messaging'
      fullPath: '/messaging'
      preLoaderRoute: typeof MessagingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$sessionId': {
      id: '/c/$sessionId'
      path: '/c/$sessionId'
      fullPath: '/c/$sessionId'
      preLoaderRoute: typeof CSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtifactsRoute: ArtifactsRoute,
  BotsRoute: BotsRoute,
  CapabilitiesRoute: CapabilitiesRoute,
  JobsRoute: JobsRoute,
  KanbanRoute: KanbanRoute,
  MemoryRoute: MemoryRoute,
  MessagingRoute: MessagingRoute,
  SettingsRoute: SettingsRoute,
  StatusRoute: StatusRoute,
  CSessionIdRoute: CSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
